server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/imdb_reviews
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: imdb-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.imdb.processor.model.ReviewMessage

logging:
  level:
    com.imdb.processor: DEBUG
    org.springframework.kafka: DEBUG